global function CRMframeworkAddSetings

void function CRMframeworkAddSetings(){
	AddModTitle("Custom Reticle Mod - vmt UI Framework")
	AddModCategory("GLOBAL SETTINGS")
	AddConVarSettingEnum("CRM.offset_disable", "Reticle Offset Killswitch", ["Off", "On"])
	AddConVarSettingEnum("CRM.cstm_color_override", "Custom color overrides colourblind settings", ["Off", "On"])
	AddConVarSettingEnum("CRM.rgb_override", "RGB mode", ["Off", "On"])
	AddModCategory("temp!FOV Presets [type 'exec crf_fov' in console]")
	AddModCategory("Universal Scopes [close/mid range]")
	AddModCategory("HCOG2 [R201;R101;HEMLOK;G2;V-47;ALTERNATOR]")
	AddConVarSetting("CRM.hcog2_base_colorR", "Red color intensity", "float")
	AddConVarSetting("CRM.hcog2_base_colorG", "Green color intensity", "float")
	AddConVarSetting("CRM.hcog2_base_colorB", "Blue color intensity", "float")
	AddConVarSetting("CRM.hcog2_reticle_scale","Front Reticle Scale", "float")
	AddConVarSetting("CRM.hcog2_offset_scalar","Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.hcog2_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddModCategory("ACGS [UNIVERSAL]")
	AddConVarSetting("CRM.acgs_base_colorR", "Red color intensity", "float")
	AddConVarSetting("CRM.acgs_base_colorG", "Green color intensity", "float")
	AddConVarSetting("CRM.acgs_base_colorB", "Blue color intensity", "float")
	AddConVarSetting("CRM.acgs_reticle_scale","Front Reticle Scale", "float")
	AddConVarSetting("CRM.acgs_offset_scalar","Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.acgs_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddModCategory("AOG_R1 [R101]")
	AddConVarSetting("CRM.aog_r1_base_colorR", "Red color intensity", "float")
	AddConVarSetting("CRM.aog_r1_base_colorG", "Green color intensity", "float")
	AddConVarSetting("CRM.aog_r1_base_colorB", "Blue color intensity", "float")
	AddConVarSetting("CRM.aog_r1_reticle_scale","Front Reticle Scale", "float")
	AddConVarSetting("CRM.aog_r1_offset_scalar","Offset Strength multiplier","float")
	AddModCategory("AOG_R2 [SPITFIRE;LSTAR;DEVOTION]")
	AddConVarSetting("CRM.aog_r2_base_colorR", "Red color intensity", "float")
	AddConVarSetting("CRM.aog_r2_base_colorG", "Green color intensity", "float")
	AddConVarSetting("CRM.aog_r2_base_colorB", "Blue color intensity", "float")
	AddConVarSetting("CRM.aog_r2_reticle_scale","Front Reticle Scale", "float")
	AddConVarSetting("CRM.aog_r2_offset_scalar","Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.aog_r2_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddModCategory("THREAT_SCOPE [R201;R101;HEMLOK;G2;V-47;SPITFIRE;LSTAR;DEVOTION]")
	AddConVarSetting("CRM.cro_base_colorR", "Red color intensity", "float")
	AddConVarSetting("CRM.cro_base_colorG", "Green color intensity", "float")
	AddConVarSetting("CRM.cro_base_colorB", "Blue color intensity", "float")
	AddConVarSetting("CRM.cro_reticle_scale","Front Reticle Scale", "float")
	AddConVarSetting("CRM.cro_offset_scalar","Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.cro_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddModCategory("HOLO_R2 [CAR;VOLT;R97]")
	AddConVarSetting("CRM.holo_r2_base_colorR", "Red color intensity", "float")
	AddConVarSetting("CRM.holo_r2_base_colorG", "Green color intensity", "float")
	AddConVarSetting("CRM.holo_r2_base_colorB", "Blue color intensity", "float")
	AddConVarSetting("CRM.holo_r2_reticle_scale","Front Reticle Scal", "float")
	AddConVarSetting("CRM.holo_r2_offset_scalar","Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.holo_r2_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddModCategory("CQH SIGHT [WINGMAN;WINGMAN_E;MOZAMBIQUE]")
	AddConVarSetting("CRM.cqh_base_colorR", "Red color intensity", "float")
	AddConVarSetting("CRM.cqh_base_colorG", "Green color intensity", "float")
	AddConVarSetting("CRM.cqh_base_colorB", "Blue color intensity", "float")
	AddConVarSetting("CRM.cqh_reticle_scale","Front Reticle Scale", "float")
	AddConVarSetting("CRM.cqh_offset_scalar","Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.cqh_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddModCategory("HCOG1 [Titanfall 1 hcog]")
	AddConVarSetting("CRM.hcog1_base_colorR", "Red color intensity", "float")
	AddConVarSetting("CRM.hcog1_base_colorG", "Green color intensity", "float")
	AddConVarSetting("CRM.hcog1_base_colorB", "Blue color intensity", "float")
	AddConVarSetting("CRM.hcog1_reticle_scale","Front Reticle Scale", "float")
	AddConVarSetting("CRM.hcog1_offset_scalar","Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.hcog1_reticle_style","Front reticle style [0-7]", 0, 7, 1, true)
	AddModCategory("IRON SIGHTS [ARs]")
	AddConVarSetting("CRM.r201_front_base_colorR", "R201 Red color intensity", "float")
	AddConVarSetting("CRM.r201_front_base_colorG", "R201 Green color intensity", "float")
	AddConVarSetting("CRM.r201_front_base_colorB", "R201 Blue color intensity", "float")
	AddConVarSetting("CRM.r201_front_reticle_scale","R201 Front Reticle Scale", "float")
	AddConVarSetting("CRM.r201_front_offset_scalar","R201 Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.r201_front_reticle_style","R201 Front reticle style [0-7]", 0, 7, 1, true)
	AddConVarSetting("CRM.hemlok_front_base_colorR", "R201 Red color intensity", "float")
	AddConVarSetting("CRM.hemlok_front_base_colorG", "R201 Green color intensity", "float")
	AddConVarSetting("CRM.hemlok_front_base_colorB", "R201 Blue color intensity", "float")
	AddConVarSetting("CRM.hemlok_front_reticle_scale","R201 Front Reticle Scale", "float")
	AddConVarSetting("CRM.hemlok_front_offset_scalar","R201 Offset Strength multiplier","float")
	AddConVarSettingSlider("CRM.hemlok_front_reticle_style","R201 Front reticle style [0-7]", 0, 7, 1, true)
	AddModCategory("IRON SIGHTS [SMGs]")
	AddModCategory("IRON SIGHTS [LMGs]")
	AddModCategory("IRON SIGHTS [SNIPERs]")
	
}